name: Tests

on:
  workflow_call:
    inputs:
      source_sha:
        required: true
        type: string
    secrets:
      HF_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  cpu:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.source_sha }}
      - name: Cache models
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/huggingface/hub
          key: models-v1-${{ runner.os }}-aa8c91ca-1a793eb5-e4e9ddf2
      - name: Cache Cargo
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: test-v3-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: test-v3-${{ runner.os }}-
      - name: Test
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: cargo test --release --locked --no-default-features --features cpu

  metal:
    runs-on: macos-15
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.source_sha }}
      - name: Cache models
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/huggingface/hub
          key: models-v1-${{ runner.os }}-aa8c91ca-1a793eb5-e4e9ddf2
      - name: Cache Cargo
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: test-v3-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: test-v3-${{ runner.os }}-
      - name: Test
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: cargo test --release --locked --no-default-features --features metal
