name: Tests

on:
  workflow_call:
    secrets:
      HF_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  cpu:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/huggingface/hub
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: test-cpu-${{ hashFiles('Cargo.lock') }}-aa8c91ca088ec597df95a0d1c76b3063cb2ae5e8
          restore-keys: test-cpu-
      - name: Test
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: cargo test --release --locked --no-default-features --features cpu

  metal:
    runs-on: macos-14
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/huggingface/hub
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: test-metal-${{ hashFiles('Cargo.lock') }}-aa8c91ca088ec597df95a0d1c76b3063cb2ae5e8
          restore-keys: test-metal-
      - name: Test
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: cargo test --release --locked --no-default-features --features metal
